/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: openvent.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "openvent.pb-c.h"
void   device_info__init
                     (DeviceInfo         *message)
{
  static const DeviceInfo init_value = DEVICE_INFO__INIT;
  *message = init_value;
}
size_t device_info__get_packed_size
                     (const DeviceInfo *message)
{
  assert(message->base.descriptor == &device_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t device_info__pack
                     (const DeviceInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &device_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t device_info__pack_to_buffer
                     (const DeviceInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &device_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DeviceInfo *
       device_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DeviceInfo *)
     protobuf_c_message_unpack (&device_info__descriptor,
                                allocator, len, data);
}
void   device_info__free_unpacked
                     (DeviceInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &device_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   file_data__init
                     (FileData         *message)
{
  static const FileData init_value = FILE_DATA__INIT;
  *message = init_value;
}
size_t file_data__get_packed_size
                     (const FileData *message)
{
  assert(message->base.descriptor == &file_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t file_data__pack
                     (const FileData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &file_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t file_data__pack_to_buffer
                     (const FileData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &file_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FileData *
       file_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FileData *)
     protobuf_c_message_unpack (&file_data__descriptor,
                                allocator, len, data);
}
void   file_data__free_unpacked
                     (FileData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &file_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vent_data__init
                     (VentData         *message)
{
  static const VentData init_value = VENT_DATA__INIT;
  *message = init_value;
}
size_t vent_data__get_packed_size
                     (const VentData *message)
{
  assert(message->base.descriptor == &vent_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vent_data__pack
                     (const VentData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vent_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vent_data__pack_to_buffer
                     (const VentData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vent_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
VentData *
       vent_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (VentData *)
     protobuf_c_message_unpack (&vent_data__descriptor,
                                allocator, len, data);
}
void   vent_data__free_unpacked
                     (VentData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vent_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vent_request__init
                     (VentRequest         *message)
{
  static const VentRequest init_value = VENT_REQUEST__INIT;
  *message = init_value;
}
size_t vent_request__get_packed_size
                     (const VentRequest *message)
{
  assert(message->base.descriptor == &vent_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vent_request__pack
                     (const VentRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vent_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vent_request__pack_to_buffer
                     (const VentRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vent_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
VentRequest *
       vent_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (VentRequest *)
     protobuf_c_message_unpack (&vent_request__descriptor,
                                allocator, len, data);
}
void   vent_request__free_unpacked
                     (VentRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vent_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vent_response__init
                     (VentResponse         *message)
{
  static const VentResponse init_value = VENT_RESPONSE__INIT;
  *message = init_value;
}
size_t vent_response__get_packed_size
                     (const VentResponse *message)
{
  assert(message->base.descriptor == &vent_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vent_response__pack
                     (const VentResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vent_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vent_response__pack_to_buffer
                     (const VentResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vent_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
VentResponse *
       vent_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (VentResponse *)
     protobuf_c_message_unpack (&vent_response__descriptor,
                                allocator, len, data);
}
void   vent_response__free_unpacked
                     (VentResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vent_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor device_info__field_descriptors[4] =
{
  {
    "fw_version",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceInfo, fw_version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hw_version",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceInfo, hw_version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_model",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DeviceInfo, device_model),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_name",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceInfo, device_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned device_info__field_indices_by_name[] = {
  2,   /* field[2] = device_model */
  3,   /* field[3] = device_name */
  0,   /* field[0] = fw_version */
  1,   /* field[1] = hw_version */
};
static const ProtobufCIntRange device_info__number_ranges[1 + 1] =
{
  { 2, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor device_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DeviceInfo",
  "DeviceInfo",
  "DeviceInfo",
  "",
  sizeof(DeviceInfo),
  4,
  device_info__field_descriptors,
  device_info__field_indices_by_name,
  1,  device_info__number_ranges,
  (ProtobufCMessageInit) device_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor file_data__field_descriptors[5] =
{
  {
    "file_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(FileData, file_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "file_size",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(FileData, file_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "offset",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(FileData, offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "checksum",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(FileData, checksum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(FileData, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned file_data__field_indices_by_name[] = {
  3,   /* field[3] = checksum */
  4,   /* field[4] = data */
  0,   /* field[0] = file_name */
  1,   /* field[1] = file_size */
  2,   /* field[2] = offset */
};
static const ProtobufCIntRange file_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor file_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FileData",
  "FileData",
  "FileData",
  "",
  sizeof(FileData),
  5,
  file_data__field_descriptors,
  file_data__field_indices_by_name,
  1,  file_data__number_ranges,
  (ProtobufCMessageInit) file_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vent_data__field_descriptors[3] =
{
  {
    "breath_circulating_volumn",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(VentData, breath_circulating_volumn),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "breathing_frequency",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(VentData, breathing_frequency),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "breath_in_time",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(VentData, breath_in_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vent_data__field_indices_by_name[] = {
  0,   /* field[0] = breath_circulating_volumn */
  2,   /* field[2] = breath_in_time */
  1,   /* field[1] = breathing_frequency */
};
static const ProtobufCIntRange vent_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor vent_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "VentData",
  "VentData",
  "VentData",
  "",
  sizeof(VentData),
  3,
  vent_data__field_descriptors,
  vent_data__field_indices_by_name,
  1,  vent_data__number_ranges,
  (ProtobufCMessageInit) vent_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vent_request__field_descriptors[4] =
{
  {
    "cmd",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(VentRequest, cmd),
    &command__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "access_key",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(VentRequest, access_key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "read_firmware_request",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(VentRequest, read_firmware_request),
    &file_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "write_firmware_request",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(VentRequest, write_firmware_request),
    &file_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vent_request__field_indices_by_name[] = {
  1,   /* field[1] = access_key */
  0,   /* field[0] = cmd */
  2,   /* field[2] = read_firmware_request */
  3,   /* field[3] = write_firmware_request */
};
static const ProtobufCIntRange vent_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor vent_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "VentRequest",
  "VentRequest",
  "VentRequest",
  "",
  sizeof(VentRequest),
  4,
  vent_request__field_descriptors,
  vent_request__field_indices_by_name,
  1,  vent_request__number_ranges,
  (ProtobufCMessageInit) vent_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vent_response__field_descriptors[4] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(VentResponse, status),
    &status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_info_response",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(VentResponse, device_info_response),
    &device_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "read_firmware_response",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(VentResponse, read_firmware_response),
    &file_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vent_data_response",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(VentResponse, vent_data_response),
    &vent_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vent_response__field_indices_by_name[] = {
  1,   /* field[1] = device_info_response */
  2,   /* field[2] = read_firmware_response */
  0,   /* field[0] = status */
  3,   /* field[3] = vent_data_response */
};
static const ProtobufCIntRange vent_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor vent_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "VentResponse",
  "VentResponse",
  "VentResponse",
  "",
  sizeof(VentResponse),
  4,
  vent_response__field_descriptors,
  vent_response__field_indices_by_name,
  1,  vent_response__number_ranges,
  (ProtobufCMessageInit) vent_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue status__enum_values_by_number[3] =
{
  { "Unknown", "STATUS__Unknown", 0 },
  { "Success", "STATUS__Success", 1 },
  { "Fail", "STATUS__Fail", 2 },
};
static const ProtobufCIntRange status__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex status__enum_values_by_name[3] =
{
  { "Fail", 2 },
  { "Success", 1 },
  { "Unknown", 0 },
};
const ProtobufCEnumDescriptor status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Status",
  "Status",
  "Status",
  "",
  3,
  status__enum_values_by_number,
  3,
  status__enum_values_by_name,
  1,
  status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue command__enum_values_by_number[6] =
{
  { "CmdNone", "COMMAND__CmdNone", 0 },
  { "CmdDeviceInfoRequest", "COMMAND__CmdDeviceInfoRequest", 1 },
  { "CmdVentDataRequest", "COMMAND__CmdVentDataRequest", 2 },
  { "CmdCheckFirmwareRequest", "COMMAND__CmdCheckFirmwareRequest", 3 },
  { "CmdWriteFirmwareRequest", "COMMAND__CmdWriteFirmwareRequest", 4 },
  { "CmdReadFirmwareRequest", "COMMAND__CmdReadFirmwareRequest", 5 },
};
static const ProtobufCIntRange command__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex command__enum_values_by_name[6] =
{
  { "CmdCheckFirmwareRequest", 3 },
  { "CmdDeviceInfoRequest", 1 },
  { "CmdNone", 0 },
  { "CmdReadFirmwareRequest", 5 },
  { "CmdVentDataRequest", 2 },
  { "CmdWriteFirmwareRequest", 4 },
};
const ProtobufCEnumDescriptor command__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Command",
  "Command",
  "Command",
  "",
  6,
  command__enum_values_by_number,
  6,
  command__enum_values_by_name,
  1,
  command__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
